version: '3.7'

services:
  node:
    build:
      context: .  #where to find ur docker file, '.' means current dir
      dockerfile: Dockerfile
      target: base
    volumes:
      - .:/usr/src/app
    container_name: node-test
    ports:
      - '4000:4000'
    command: npm run start